name: CI

on:
  workflow_dispatch:

jobs:
  prepear_to_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Simulate a Build
        run: echo 'Terraform plan'

  deploy:
    runs-on: ubuntu-latest
    needs: [prepear_to_deploy]
    environment: 
      name: dev
      url: 'https://test.com'
    steps:
      - name: deploy Dev
        run: echo "Deploy dev!!!"
        
