name: CI

on:
  workflow_dispatch:

jobs:
  prepear_to_deploy:
    runs-on: ubuntu-latest
    steps: 

      - name: Simulate a Build
        run: echo 'Terraform plan'

  open-issue:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [prepear_to_deploy]
    outputs:
      ISSUE-NUMBER: ${{ steps.create-issue.outputs.number }}
    steps:

    - uses: actions/checkout@v2
    
    - name: Create an issue
      uses: JasonEtco/create-an-issue@v2
      id: create-issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ENVIRONMENT: Dev
        RUNNUMBER: ${{ github.run_number  }}
      with:         
        filename: .github/deployment-approval.md
    - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'

  deploy:
    runs-on: ubuntu-latest
    needs: [prepear_to_deploy, open-issue]
    environment: 
      name: dev
      url: 'https://test.com'
    steps:

      - name: deploy Dev
        run: echo "Deploy dev!!!"
        
  # close-issue:
  #   permissions: write-all
  #   needs: [deploy]
  #   if: ${{ always() }}
  #   runs-on: ubuntu-latest  
  #   steps:

  #     - name: Close Issue
  #       if: ${{ needs.deploy.result == 'success' }}
  #       uses: peter-evans/close-issue@v3
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         issue-number: ${{ github.event.issue.number }}
  #         comment: 'Deployment Completed 🌟'