name: CI

on:
  workflow_dispatch:

jobs:
  prepear_to_deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2

      - name: Simulate a Build
        run: echo 'Terraform plan'

      - name: Create an issue
        uses: JasonEtco/create-an-issue@v2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: Dev
          RUNNUMBER: ${{ github.run_number  }}
        with:         
          filename: .github/deployment-approval.md

  deploy:
    runs-on: ubuntu-latest
    needs: [prepear_to_deploy]
    environment: 
      name: dev
      url: 'https://test.com'
    steps:
      - name: deploy Dev
        run: echo "Deploy dev!!!"
        
