name: CI

on:
  workflow_dispatch:

jobs:
  prepear_to_deploy:
    runs-on: ubuntu-latest
    steps: 

      - name: Simulate a Build
        run: echo 'Terraform plan'

  open-issue:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [prepear_to_deploy]
    steps:

    - uses: actions/checkout@v2
    
    - name: Create an issue
      uses: JasonEtco/create-an-issue@v2.6.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ENVIRONMENT: Dev
        RUNNUMBER: ${{ github.run_number  }}
      with:         
        filename: .github/deployment-approval.md

  deploy:
    runs-on: ubuntu-latest
    needs: [prepear_to_deploy, open-issue]
    environment: 
      name: dev
      url: 'https://test.com'
    steps:

      - name: deploy Dev
        run: echo "Deploy dev!!!"
        

  close-issue:
    permissions: write-all
    needs: [deploy]
    if: ${{ always() }}
    runs-on: ubuntu-latest  
    steps:

      - name: Close Issue
        if: ${{ needs.deploy.result == 'success' }}
        uses: peter-evans/close-issue@v1.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Deployment Completed 🌟'